#Variaveis Globais
IDS = {
    'ITABIRA': '5b91aec2-e7ae-45e8-8146-bb7e5c40a8b6',
    'BOM DESPACHO': 'b4c0bf14-2472-4f48-ae5e-5c16e5e592ed',
    'PEQUI': 'a09d7656-f2a0-4b33-8c12-c8a4580e5e9d'
    }

MODELOJSON = [{
    "id":"39060838-30c6-4481-99c8-daf898561002",
    "cityId":None,
    "nomeCompleto":None,
    "cpf":None,
    "rg":None,
    "dataNasc":None,
    "usoDeDados":None,
    "genero":None,
    "pcd":None,
    "preferredName":None,
    "hasPreferredName":None,
    "cep":None,
    "rua":None,
    "cityName":None,
    "motherName":None,
    "bairro":None,
    "numero":None,
    "complemento":None,
    "cel":None,
    "celResponsavel":None,
    "operadora":None,
    "homeInternetAccess":None,
    "email":None,
    "profissao":None,
    "estadoCivil":None,
    "religiao":None,
    "rendaFamiliar":None,
    "escolaPublica":None,
    "raca":None,
    "escolaridade":None,
    "previousKnowledge":None,
    "nomeFaculdade":None,
    "periodoFaculdade":None,
    "schoolYear":None,
    "cota":None,
    "tipoPcd":None,
    "cadastroCompleto":None,
    "practiceTestId":None,
    "testId":None,
    "absent":None,
    "score":None,
    "parent":None,
    "disqualified":None,
    "enrolled":None,
    "documentsValidated":None,
    "nOfChildren":None,
    "youngestNascDate":None,
    "schoolAward":None,
    "emailPd":None,
    "notePatrimony":None,
    "createdAt":None,
    "examHour":None
}]
